const canvas=document.getElementById("antigravityCanvas"),ctx=canvas.getContext("2d");let w,h,dpr,particles=[],mouse={x:.5,y:.5,tx:.5,ty:.5};const colors=["#4285f4","#ea4335","#fbbc05","#34a853","#7b61ff","#00c9a7"];function resize(){dpr=Math.min(devicePixelRatio||1,1.5);w=canvas.width=innerWidth*dpr;h=canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";particles=Array.from({length:Math.min(900,Math.floor(innerWidth*innerHeight/1200))},(_,i)=>({x:Math.random()*w,y:Math.random()*h,a:Math.random()*Math.PI*2,r:20+Math.random()*240,s:.25+Math.random()*.85,l:(3+Math.random()*8)*dpr,o:.28+Math.random()*.5,c:colors[i%colors.length]}))}function draw(){ctx.clearRect(0,0,w,h);mouse.x+=(mouse.tx-mouse.x)*.05;mouse.y+=(mouse.ty-mouse.y)*.05;let t=performance.now()/1000;let mx=(mouse.x-.5)*28*dpr,my=(mouse.y-.5)*28*dpr;for(const p of particles){p.a+=0.0009*p.s;let wave=Math.sin(t*p.s+p.x*.002)*12*dpr;let x=p.x+Math.cos(p.a)*wave+mx;let y=p.y+Math.sin(p.a*1.2)*wave+my;if(x<0)x+=w;if(x>w)x-=w;if(y<0)y+=h;if(y>h)y-=h;ctx.save();ctx.translate(x,y);ctx.rotate(p.a+Math.sin(t+p.y*.002)*.8);ctx.globalAlpha=p.o;ctx.strokeStyle=p.c;ctx.lineWidth=1.05*dpr;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-p.l/2,0);ctx.lineTo(p.l/2,0);ctx.stroke();ctx.restore()}requestAnimationFrame(draw)}resize();draw();window.addEventListener("resize",resize);window.addEventListener("mousemove",e=>{mouse.tx=e.clientX/innerWidth;mouse.ty=e.clientY/innerHeight});
const nav=document.getElementById("nav"),progress=document.getElementById("progress");window.addEventListener("scroll",()=>{let total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/total*100)+"%";nav.classList.toggle("shrink",scrollY>40);activeNav()});
document.getElementById("menu").addEventListener("click",()=>document.getElementById("links").classList.toggle("open"));document.querySelectorAll(".links a").forEach(a=>a.addEventListener("click",()=>document.getElementById("links").classList.remove("open")));
const typed=document.getElementById("typed"),words=["ML Projects","Data Dashboards","AI Apps","GenAI Workflows","Python Tools"];let wi=0,ci=0,del=false;function type(){let word=words[wi];typed.textContent=word.slice(0,ci);if(!del&&ci<word.length)ci++;else if(del&&ci>0)ci--;else{del=!del;if(!del)wi=(wi+1)%words.length}setTimeout(type,del?45:85)}type();
const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");if(e.target.classList.contains("skill"))e.target.querySelector("i").style.width=e.target.dataset.level+"%";if(e.target.classList.contains("hero-copy"))counters()}})},{threshold:.16});document.querySelectorAll(".reveal,.skill").forEach(el=>obs.observe(el));let counted=false;function counters(){if(counted)return;counted=true;document.querySelectorAll("[data-count]").forEach(el=>{let target=+el.dataset.count,n=0,step=Math.max(1,Math.ceil(target/70));let timer=setInterval(()=>{n+=step;if(n>=target){n=target;clearInterval(timer)}el.textContent=n+(target<100?"+":"")},18)})}
document.querySelectorAll(".tilt").forEach(card=>{card.addEventListener("mousemove",e=>{let r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg) translateY(-7px)`});card.addEventListener("mouseleave",()=>card.style.transform="")});
document.querySelectorAll("[data-slide]").forEach(btn=>btn.addEventListener("click",()=>document.getElementById(btn.dataset.slide).scrollBy({left:btn.dataset.dir*330,behavior:"smooth"})));const lb=document.getElementById("lightbox"),lbi=document.getElementById("lightboxImg");
document.querySelectorAll(".doc-btn").forEach(btn=>{
  btn.addEventListener("click",e=>{
    e.preventDefault();
    const proofSrc = btn.dataset.proof;
    if(!proofSrc) return;
    lbi.src = proofSrc;
    lb.classList.add("open");
  });
});
document.querySelectorAll(".proof-card img").forEach(img=>img.addEventListener("click",()=>{lbi.src=img.src;lb.classList.add("open")}));document.getElementById("closeLightbox").addEventListener("click",()=>lb.classList.remove("open"));lb.addEventListener("click",e=>{if(e.target===lb)lb.classList.remove("open")});const sections=[...document.querySelectorAll("section[id]")],navItems=[...document.querySelectorAll(".links a")];function activeNav(){let current="home";sections.forEach(sec=>{if(scrollY>=sec.offsetTop-150)current=sec.id});navItems.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+current))}
